import { Card, Button } from '@nclex/shared-ui';
import Link from 'next/link';

export default function LandingPage() {
    return (
        <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
            {/* Hero Section */}
            <div className="px-4 py-20 text-center">
                <h1 className="text-5xl md:text-6xl font-extrabold text-blue-900 mb-6 tracking-tight">
                    Pass the NCLEX NGN <br />
                    <span className="text-blue-600">The First Time</span>
                </h1>
                <p className="text-xl text-gray-600 mb-10 max-w-2xl mx-auto leading-relaxed">
                    Experience the most realistic NGN practice platform.
                    AI-powered case studies, detailed rationales, and adaptive learning.
                </p>
                <div className="flex justify-center gap-4">
                    <Link href="/trial">
                        <Button className="px-8 py-4 text-lg shadow-xl hover:shadow-2xl transform hover:-translate-y-1 transition-all">
                            Start Free Trial
                        </Button>
                    </Link>
                    <a href="#" className="px-8 py-4 text-lg font-medium text-blue-600 hover:text-blue-800 transition-colors">
                        View Pricing
                    </a>
                </div>
            </div>

            {/* Features Grid */}
            <div className="max-w-6xl mx-auto px-4 py-16">
                <div className="grid md:grid-cols-3 gap-8">
                    <Card className="p-8 hover:shadow-lg transition-shadow border-t-4 border-blue-500">
                        <div className="text-4xl mb-4">🧠</div>
                        <h3 className="text-xl font-bold text-gray-900 mb-3">AI Case Studies</h3>
                        <p className="text-gray-600">
                            Practice with unlimited, unique NGN case studies generated by advanced AI.
                        </p>
                    </Card>
                    <Card className="p-8 hover:shadow-lg transition-shadow border-t-4 border-purple-500">
                        <div className="text-4xl mb-4">🎯</div>
                        <h3 className="text-xl font-bold text-gray-900 mb-3">Smart Rationales</h3>
                        <p className="text-gray-600">
                            Understand the "why" behind every answer with deep clinical explanations.
                        </p>
                    </Card>
                    <Card className="p-8 hover:shadow-lg transition-shadow border-t-4 border-green-500">
                        <div className="text-4xl mb-4">📈</div>
                        <h3 className="text-xl font-bold text-gray-900 mb-3">Performance Tracking</h3>
                        <p className="text-gray-600">
                            Visualize your progress and identify weak areas before exam day.
                        </p>
                    </Card>
                </div>
            </div>

            {/* Social Proof */}
            <div className="bg-white py-16 border-t border-gray-100">
                <div className="max-w-4xl mx-auto px-4 text-center">
                    <h2 className="text-3xl font-bold text-gray-900 mb-8">Trusted by Nursing Students</h2>
                    <div className="grid md:grid-cols-2 gap-8">
                        <div className="p-6 bg-gray-50 rounded-xl">
                            <p className="text-gray-600 italic mb-4">"The case studies are exactly like the real thing. I felt so much more confident walking into the exam."</p>
                            <p className="font-bold text-gray-900">- Sarah J., RN</p>
                        </div>
                        <div className="p-6 bg-gray-50 rounded-xl">
                            <p className="text-gray-600 italic mb-4">"I love the AI explanations. It's like having a personal tutor available 24/7."</p>
                            <p className="font-bold text-gray-900">- Michael T., BSN Student</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
